name: Limit CCN and File Size

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 5
      
    - name: Check size
      run: |
        $HOME/.local/bin/lizard | bash .github/workflows/lpar.sh 50
